apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: meetup-app-prod
  name: meetup-app-prod
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meetup-app-prod
  template:
    metadata:
      labels:
        app: meetup-app-prod
    spec:
      containers:
      - image: registry.hub.docker.com/arunvarghe/meetup:latest
        imagePullPolicy: Always
        name: meetup-app-prod
        ports:
        - containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: meetup-app-prod-service
spec:
  selector:
    app: meetup-app-prod
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 9000
    targetPort: 9000